### ISSUE TITLE
`System.TypeLoadException` with Minimal Project Setup

### ISSUE THREAD

**Issue by thygrrr** [DaveGreen-Games/ShapeEngine#27]
## What:
Can't run the basic example (fails early at runtime)
- Windows 11 64 bits
- .NET 8.0 and 7.0
- Rider 2024 and dotnet Command Line

## Repro:
[minimal-repro.zip](https://github.com/DaveGreen-Games/ShapeEngine/files/15496738/minimal-repro.zip)

## How:
I created a new project like so (also tried .net7.0) and also omitting `--use-program-main`:

```powershell
dotnet new console --framework net8.0 --use-program-main 
dotnet add package DaveGreen.ShapeEngine
```

And pasted in the example from [Minimal Project Setup](https://github.com/DaveGreen-Games/ShapeEngine?tab=readme-ov-file#minimal-project-setup).

Unfortunately, at runtime (launched from Rider), it gives me...
```
Unhandled exception. System.TypeLoadException: Could not load type 'ShapeEngine.Core.Structs.GameSettings' from assembly 'shapeengine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ShapeEngineProject.Program.Main(String[] args)

Process finished with exit code -532,462,766.
```

**Comment by thygrrr** [comment]
Same happens from command line:
```powershell
PS P:\fennECS\demos\shapeengine> dotnet run
Unhandled exception. System.TypeLoadException: Could not load type 'ShapeEngine.Core.Structs.GameSettings' from assembly 'shapeengine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at fennecs.shape.demo.Program.Main(String[] args)
PS P:\fennECS\demos\shapeengine>
```

**Comment by thygrrr** [comment]
Occasionally I get a:
```
P:/fennECS/demos/shapeengine/bin/Debug/net8.0/shapeengine.exe
Unhandled exception. System.MissingMethodException: Entry point not found in assembly 'ShapeEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

**Comment by thygrrr** [comment]
Chances are that the project can EXPLICITLY not be named "shapeengine.csproj".

Though I've never seen this with a package before. :)

## Working Repro:
[working-demo-shapeengine.zip](https://github.com/DaveGreen-Games/ShapeEngine/files/15497223/working-demo-shapeengine.zip)

**Comment by SoloByte** [comment]
After looking at it and testing it I think you are right. In the repository the shape engine project is called "ShapeEngine" therefore the csproj file is called "ShapeEngine.csproj". If you create a project called shapeengine and the system is not case sensitive then it might be problem... I renamed the non-working project and tested it and it works fine.

**Comment by SoloByte** [comment]
I think there is no solution to this, because it is working correctly ? I am closing this for now.
