### ISSUE TITLE
Build on Linux or macOS

### ISSUE THREAD

**Issue by AlexKordic** [DaveGreen-Games/ShapeEngine#42]
Hi,

Can I try ShapeEngine on Linux or macbook computer?

On windows visual studio makes this process simple.

**Comment by SoloByte** [comment]
Basically you need an IDE for c# that runs on Mac or Linux to be able to have the simple setup with the Shape Engine nuget package.

I am using JetBrains rider for macOS and itis available for Linux & windows as well. 

Visual Studio Code is also an alternative (and it is free) but the setup is more complicated.

**Comment by AlexKordic** [comment]
Rider IDE is working for me on macOS.

Thank you.
