### ISSUE TITLE
HTML5 Exports ? 

### ISSUE THREAD

**Issue by Mylab6** [DaveGreen-Games/ShapeEngine#43]
Hi, just asking if this is at all possible. I definitely love the look and design of the engine!

**Comment by SoloByte** [comment]
Honestly, I don´t know :( 
I don´t need it so I have never looked into it. 

Raylib can be exported for web so you would have to look into how to export c# projects for HTML5.

**Comment by Mylab6** [comment]
Thanks for the response! 

If I ever figure this out I'll open a PR.
